# These files contain URLs to download input files
# curl reads them with -K option. 
# Those can contain parameters and protocols which curl supports.
# You can change path to a local file, which points to the urls found 
# in the comments below.

curl_fastq_urls:
  class: File
  path: http://86.50.168.37:8000/fastq_files_urls.txt

# ftp://ftp-trace.ncbi.nih.gov/giab/ftp/data/NA12878/NIST_NA12878_HG001_HiSeq_300x/140407_D00360_0017_BH947YADXX/Project_RM8398/Sample_U5c/U5c_CCGTCC_L001_R1_001.fastq.gz
# ftp://ftp-trace.ncbi.nih.gov/giab/ftp/data/NA12878/NIST_NA12878_HG001_HiSeq_300x/140407_D00360_0017_BH947YADXX/Project_RM8398/Sample_U5c/U5c_CCGTCC_L001_R2_001.fastq.gz 

curl_reference_genome_url:
  class: File
  path: http://86.50.168.37:8000/reference_seq_url.txt
# ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/phase2_reference_assembly_sequence/hs37d5.fa.gz

curl_known_indels_url:
  class: File
  path: http://86.50.168.37:8000/known_indels_url.txt

# ftp://ftp.broadinstitute.org/bundle/b37/Mills_and_1000G_gold_standard.indels.b37.vcf.gz

curl_known_sites_url:
  class: File
  path: http://86.50.168.37:8000/known_sites_url.txt

# ftp://ftp.broadinstitute.org/bundle/b37/dbsnp_138.b37.vcf.gz

# This is the configuration files to download the output files for lftp client.
# You may comment the step away from your workflow 
lftp_out_conf:
  class: File
  path: http://86.50.168.37:8000/lftp.txt

# this is for BWA. This string was used at BSC for the same pipeline
readgroup_str: '@RG\tID:Seq01p\tSM:Seq01\tPL:ILLUMINA\tPI:330'
sample_name: 'abc1'
threads:  "10"
gqb: [20, 25, 30, 35, 40, 45, 50, 70, 90, 99]
# GATK Haplotype caller sequence
#chromosome: '1'
